# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f683842d8af7e2b90d850e1a9460f2648b360d791fe6d5dd6ffbc85f1f8bffb072419c2ef7b2f98cf2980f09615ee5cb292d46378873aeb3e3b895722eeb8b05

test:
  secret_key_base: 6976b8a047de52d934a065a17af68951afeacd0e89c56377b6caf2967e9affefd59513de7bea68af25c8dcc8b3cad977e1805f28ed78ed3959b460633f5f0a78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
